### ISSUE TITLE
Considerations for @StateObject and App declarations

### ISSUE THREAD

**Issue by OskarGroth** [roboheadz/swiftui-router#11]
Hi! I've been searching for a scalable architecture for SwiftUI projects for a while now and I'm very impressed by this pattern so far. I'm working on implementing it into a new project, and there are some thoughts that I had while working with it:

Many router views declare their router variable as `@StateObject`, which implies that _"SwiftUI creates a new instance of the object only once for each instance of the structure that declares the object"_. But when we pass this object as a parameter:

```
@ViewBuilder func loginScreen() -> some View {
    LoginRouterView(router: LoginRouter(services: self.services))
}
```

Is there a point to keeping it declared as `@StateObject` as opposed to `@ObservedObject`? It was my understanding that the `@StateObject` property wrapper is only relevant when instantiating the object inside of the view struct.

In general, I'd also consider it a smell to initiate objects in a view body/builder like this. These objects used to be declared as lazy variables on the parent router, and that code is still there but no longer used:

https://github.com/roboheadz/swiftui-router/blob/2cddc8c4b186cac818bcad56a44794417cbe2235/swiftui-router/Routers/AppRouter.swift#L26

Did you reach a new conclusion here that caused you to make this change?

Additionally, for the App struct I would propose to move from:

```
struct RouterTestApp: App {
    
    var body: some Scene {
        WindowGroup {
            AppRouterView(router: AppRouter(services: AppServices()))
        }
    }
}
```

To 

```
struct RouterTestApp: App {

    @StateObject var router = AppRouter(services: AppServices())

    var body: some Scene {
        WindowGroup {
            AppRouterView(router: router)
        }
    }
}
```

To avoid creating the object in the body, and also enable the `AppServices` to be instantiated as early as possible in the App lifecycle.

**Comment by OskarGroth** [comment]
I'm also confused as to why this object defined as `@State`, is it a typo?

https://github.com/roboheadz/swiftui-router/blob/2cddc8c4b186cac818bcad56a44794417cbe2235/swiftui-router/Screens/Account/AccountScreen.swift#L15

**Comment by roboheadz** [comment]
Hi @OskarGroth - thanks for this 🙏

_Did you reach a new conclusion here that caused you to make this change?_

Yes! So, deeper into using the original pattern with a real app with some depth (> 8 screens, several flows and routers), I had some issues.

Approach #1 was this:

```
ParentRouter {
	lazy var someRouter: SomeRouter = SomeRouter(services: self.services)

	@ViewBuilder func someFlow() -> some View {
		SomeRouterView(router: self.someRouter)
	}	
}

struct SomeRouterView: View {
	@ObservedObject var router: SomeRouter
}
```

This creates a scenario where SomeRouterView is always expecting to receive the router as a dependency, but the initialisation and lifecycle of that dependency is happening from the parent router. It means parent routers become littered with router objects, that don’t de-init when their views are no longer in use.  e.g, an onboarding flow’s router sticks around in memory after the user has  completed it.

I wasn’t happy with this, and desired routers to be more self contained.

Approach #2 was this:

```
ParentRouter {

	@ViewBuilder func someFlow() -> some View {
		let router = SomeRouter(services: self.services)
		SomeRouterView(router: router)
	}	
}

struct SomeRouterView: View {
	@StateObject var router: SomeRouter
}
```

The idea here was that I could create, and configure the router before giving it to the view, and then SwiftUI would manage it’s lifecycle in memory with the view via @StateObject.

However, this causes memory issues. It turns out that creating a router as a local variable in the view builder function, and then passing it to the router view, breaks @StateObject’s behaviour. I ended up with duplicate and zombie routers when flows are accessed multiple times.

It turns out that if you create the object inline as a parameter when creating the view, StateObject works as expected. This has given me self contained Router flows, whilst allowing the injection of the services object to each child router.

_Additionally, for the App struct I would propose to move from: …._

Yes, you can. You’d need to use @ObservedObject in the AppRouterView for it’s AppRouter variable, but this would work fine.

What I’m using myself now is this:

```
struct RouterTestApp: App {

	let services: Services = AppServices()

	var body: some Scene {
        	WindowGroup {
       			 AppRouterView(router: AppRouter(services: self.services)
	        }
    	}
}
```

_I’m also confused as to why this object defined as @State, is it a typo? Or a result of defining the protocol as an AnyObject? I’m pretty sure it won’t have the intended functionality here._

Indeed! This is left over, and unnecessary, it just needs to be a regular var. I’ll get the code updated for this, thank you!

**Comment by OskarGroth** [comment]
Thanks for explaining your reasoning! All makes sense now, and I think your new App declaration is the right way to go since I didn't account for the fact that `@StateObject` uses an autoclosure so the `AppServices` wouldn't be created earlier in my suggestion anyway. Will continue to evaluate the pattern and return with more questions 👍

**Comment by roboheadz** [comment]
No problem ! Reach out here or via twitter (davidgarywood), I really appreciate your feedback and the discussion 👍
